### ISSUE TITLE
Timeline .add time

### ISSUE THREAD

**Issue by csskiller** [willybrauner/interpol#94]
Hi Willy!

Is there a way to add an absolute time for the timeline? 

Is a little bit tedious to calculate the timmings of the last animation.

Is there a way to insert only the time that the animation has to start in the timeline? 

Thanks Willy! amazing work right here.

**Comment by willybrauner** [comment]
Can you produce an example?
But if I understand your request, it's not possible for now.

**Comment by csskiller** [comment]
An easy example can be like in gsap. 

In a timeline, you add a animation, and at the end, you can use differents ways to insert it, ( >, <, +=, -= ), and if you use a number, like 0, it will show that animation at the start of the timeline.

**Comment by willybrauner** [comment]
Ok, I see. For now, the offset argument is a relative offset to the Interpol position in the Timeline:

````
ts
tl.add({
  duration: 1000
}}
tl.add({
  duration: 1000
}, -100} // -> will start at 900ms of total duration
````

With GSAP API, the example above should be:
````ts
tl.add({
  duration: 1000
}, '-=100'} 
````

... and `number` offset should be the absolute position of the add() in the TL.

I'm not sur to implement something like this because, le most common use case is to set `0` as absolute position in order to start all Interpols from at the beginning. And in this case, I can using different Interpols without Timeline.

**Comment by csskiller** [comment]
ok, thanks Willy!

**Comment by willybrauner** [comment]
@csskiller you can test the PR example offsets 
https://codesandbox.io/p/sandbox/interpol-offsets-mpzmnf?file=%2Fsrc%2Fcomponents%2Fapp%2FApp.tsx%3A1%2C1
